name: kawal_corona
description: Aplikasi kawal covid oleh Mochamad Nizwar Syafuan
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  fl_chart: ^0.8.6
  dio: ^3.0.9 
  loading_animations: ^2.1.0 
  url_launcher: ^5.4.2
  flutter_html: ^0.11.1
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.0.0
  shimmer: ^1.1.0
  flutter_map: ^0.8.2 
  latlong: ^0.6.1 
  html_unescape: ^1.0.1+3
dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter: 
  uses-material-design: true
  assets:
    - "assets/images/"